"""Daily verification digest email — HTML + plain text."""

from __future__ import annotations

import html
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from weatherbrief.models.verification import (
    MissedWarning,
    NotableMiss,
    VerificationDigestData,
)
from weatherbrief.notify.email import SmtpConfig, send_message

logger = logging.getLogger(__name__)

# Accuracy color thresholds
_GREEN = 80.0
_AMBER = 60.0

_FONT = "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif"

_STYLE_BASE = (
    f"font-family:{_FONT}; font-size:14px; color:#1a1a1a; "
    "max-width:640px; margin:0 auto; padding:16px;"
)

_STYLE_TABLE = (
    "border-collapse:collapse; width:100%; font-size:13px; "
    "font-variant-numeric:tabular-nums;"
)

_STYLE_TH = (
    "border:1px solid #ddd; padding:6px 8px; background:#f5f5f5; "
    "text-align:left; font-weight:600;"
)

_STYLE_TD = "border:1px solid #ddd; padding:6px 8px; text-align:left;"

_STYLE_METRIC = (
    "display:inline-block; text-align:center; padding:8px 16px; "
    "background:#f8f9fa; border-radius:6px; margin:4px;"
)


def _accuracy_color(pct: float | None) -> str:
    """Return inline background-color for an accuracy cell."""
    if pct is None:
        return ""
    if pct >= _GREEN:
        return "background:#d1e7dd; color:#0f5132;"
    if pct >= _AMBER:
        return "background:#fff3cd; color:#664d03;"
    return "background:#f8d7da; color:#842029;"


def _fmt_pct(pct: float | None, count: int) -> str:
    """Format accuracy as 'XX.X% (n=NN)' or '—' if missing."""
    if pct is None or count == 0:
        return "—"
    return f"{pct:.0f}%"


def _fmt_time(dt) -> str:
    """Format datetime as 'HH:MMZ'."""
    return dt.strftime("%H:%MZ") if dt else "—"


# ---------------------------------------------------------------------------
# HTML builder
# ---------------------------------------------------------------------------


def _build_digest_html(data: VerificationDigestData) -> str:
    """Render the verification digest as an HTML email."""
    a = data.activity
    parts: list[str] = []

    parts.append(f'<div style="{_STYLE_BASE}">')

    # Header
    label = data.period_label or "Daily"
    parts.append(
        f'<h2 style="margin:0 0 16px; font-size:18px;">'
        f"FlyFun Verification Digest &mdash; {html.escape(label)}</h2>"
    )

    # --- Activity summary ---
    parts.append('<div style="margin-bottom:20px;">')
    metrics = [
        ("Flights", a.flights_verified),
        ("Completed", a.flights_completed),
        ("Airports", a.airports_observed),
        ("Observations", a.observations_collected),
        ("Cycles", a.cycles_run),
    ]
    for label_text, value in metrics:
        parts.append(
            f'<div style="{_STYLE_METRIC}">'
            f'<div style="font-size:20px; font-weight:700;">{value}</div>'
            f'<div style="font-size:11px; color:#666;">{label_text}</div>'
            f"</div>"
        )
    if a.avg_cycle_duration_ms is not None:
        parts.append(
            f'<div style="{_STYLE_METRIC}">'
            f'<div style="font-size:20px; font-weight:700;">{a.avg_cycle_duration_ms:.0f}ms</div>'
            f'<div style="font-size:11px; color:#666;">Avg cycle</div>'
            f"</div>"
        )
    parts.append("</div>")

    # --- Category accuracy table ---
    parts.append(_render_accuracy_table(data))

    # --- Notable misses ---
    if data.notable_misses:
        parts.append(_render_notable_misses(data.notable_misses))

    # --- Wind advisory ---
    parts.append(_render_wind_section(data))

    # Footer
    parts.append(
        '<p style="font-size:11px; color:#999; margin-top:24px;">'
        "Generated by FlyFun Weather verification system</p>"
    )
    parts.append("</div>")

    return "".join(parts)


def _render_accuracy_table(data: VerificationDigestData) -> str:
    """Render the model x days-out accuracy table."""
    # Build lookup: (model, days_out) -> row  for today and 7d
    today_map: dict[tuple[str, int], float | None] = {}
    today_n: dict[tuple[str, int], int] = {}
    for r in data.category_accuracy_today:
        today_map[(r.model, r.days_out)] = r.accuracy_pct
        today_n[(r.model, r.days_out)] = r.sample_count

    seven_map: dict[tuple[str, int], float | None] = {}
    for r in data.category_accuracy_7d:
        seven_map[(r.model, r.days_out)] = r.accuracy_pct

    # Collect models preserving order, TAF last
    models_set: set[str] = set()
    for r in data.category_accuracy_today + data.category_accuracy_7d:
        models_set.add(r.model)
    models = sorted(m for m in models_set if m != "TAF")
    if "TAF" in models_set:
        models.append("TAF")

    if not models:
        return '<p style="color:#666; font-style:italic;">No accuracy data available.</p>'

    days_out_cols = [d for d in (0, 1, 2, 3, 5, 7)]

    parts: list[str] = []
    parts.append(
        '<h3 style="font-size:15px; margin:20px 0 8px;">Flight Category Accuracy</h3>'
    )
    parts.append(f'<table style="{_STYLE_TABLE}">')

    # Header row
    parts.append("<tr>")
    parts.append(f'<th style="{_STYLE_TH}">Model</th>')
    for d in days_out_cols:
        parts.append(f'<th style="{_STYLE_TH} text-align:center;">D-{d}</th>')
    parts.append("</tr>")

    # Data rows
    for model in models:
        parts.append("<tr>")
        parts.append(
            f'<td style="{_STYLE_TD} font-weight:600;">'
            f"{html.escape(model.upper())}</td>"
        )
        for d in days_out_cols:
            pct = today_map.get((model, d))
            n = today_n.get((model, d), 0)
            color = _accuracy_color(pct)

            # 7-day comparison
            pct_7d = seven_map.get((model, d))
            trend = ""
            if pct is not None and pct_7d is not None:
                diff = pct - pct_7d
                if abs(diff) >= 1.0:
                    arrow = "&#9650;" if diff > 0 else "&#9660;"
                    arrow_color = "#0f5132" if diff > 0 else "#dc2626"
                    trend = (
                        f'<span style="font-size:10px; color:{arrow_color};">'
                        f" {arrow}</span>"
                    )

            cell = _fmt_pct(pct, n)
            if n > 0:
                cell += f'<span style="font-size:10px; color:#999;"> ({n})</span>'

            parts.append(
                f'<td style="{_STYLE_TD} text-align:center; {color}">'
                f"{cell}{trend}</td>"
            )
        parts.append("</tr>")

    parts.append("</table>")
    parts.append(
        '<p style="font-size:11px; color:#999; margin:4px 0 0;">'
        "Arrows show change vs 7-day rolling average</p>"
    )
    return "".join(parts)


def _render_notable_misses(misses: list[NotableMiss]) -> str:
    """Render the notable misses section."""
    parts: list[str] = []
    parts.append(
        '<h3 style="font-size:15px; margin:20px 0 8px;">Notable Misses</h3>'
    )
    parts.append(f'<table style="{_STYLE_TABLE}">')
    parts.append("<tr>")
    for h in ("ICAO", "Time", "Model", "D-out", "Observed", "Predicted", "Ceiling \u0394"):
        parts.append(f'<th style="{_STYLE_TH}">{h}</th>')
    parts.append("</tr>")

    for m in misses:
        # Highlight missed IFR in red, false alarm in amber
        is_missed_ifr = m.obs_category in _IFR_CATS and m.model_category in _VFR_CATS
        row_bg = "background:#fff0f0;" if is_missed_ifr else "background:#fffde7;"
        ceiling = f"{m.ceiling_delta_ft:+.0f}ft" if m.ceiling_delta_ft is not None else "—"

        parts.append(f'<tr style="{row_bg}">')
        parts.append(f'<td style="{_STYLE_TD} font-weight:600;">{html.escape(m.icao)}</td>')
        parts.append(f'<td style="{_STYLE_TD}">{_fmt_time(m.observation_time)}</td>')
        parts.append(f'<td style="{_STYLE_TD}">{html.escape(m.model.upper())}</td>')
        parts.append(f'<td style="{_STYLE_TD} text-align:center;">D-{m.days_out}</td>')
        parts.append(f'<td style="{_STYLE_TD} font-weight:600;">{html.escape(m.obs_category)}</td>')
        parts.append(f'<td style="{_STYLE_TD}">{html.escape(m.model_category)}</td>')
        parts.append(f'<td style="{_STYLE_TD}">{ceiling}</td>')
        parts.append("</tr>")

    parts.append("</table>")
    return "".join(parts)


_IFR_CATS = ("IFR", "LIFR")
_VFR_CATS = ("VFR", "MVFR")


def _render_wind_section(data: VerificationDigestData) -> str:
    """Render wind advisory accuracy + missed warnings."""
    parts: list[str] = []
    parts.append(
        '<h3 style="font-size:15px; margin:20px 0 8px;">Wind Advisory Accuracy</h3>'
    )

    if data.wind_advisory:
        parts.append(f'<table style="{_STYLE_TABLE}">')
        parts.append("<tr>")
        for h in ("Model", "Match Rate", "Samples"):
            parts.append(f'<th style="{_STYLE_TH}">{h}</th>')
        parts.append("</tr>")

        for w in data.wind_advisory:
            color = _accuracy_color(w.accuracy_pct)
            parts.append("<tr>")
            parts.append(
                f'<td style="{_STYLE_TD} font-weight:600;">'
                f"{html.escape(w.model.upper())}</td>"
            )
            parts.append(
                f'<td style="{_STYLE_TD} text-align:center; {color}">'
                f"{_fmt_pct(w.accuracy_pct, w.sample_count)}</td>"
            )
            parts.append(f'<td style="{_STYLE_TD} text-align:center;">{w.sample_count}</td>')
            parts.append("</tr>")
        parts.append("</table>")
    else:
        parts.append('<p style="color:#666;">No wind advisory data.</p>')

    if data.missed_warnings:
        parts.append(
            '<h4 style="font-size:13px; margin:12px 0 6px; color:#dc2626;">'
            "Missed Wind Warnings</h4>"
        )
        parts.append(f'<table style="{_STYLE_TABLE}">')
        parts.append("<tr>")
        for h in ("ICAO", "Time", "Model", "Predicted"):
            parts.append(f'<th style="{_STYLE_TH}">{h}</th>')
        parts.append("</tr>")

        for w in data.missed_warnings:
            parts.append('<tr style="background:#fff0f0;">')
            parts.append(f'<td style="{_STYLE_TD} font-weight:600;">{html.escape(w.icao)}</td>')
            parts.append(f'<td style="{_STYLE_TD}">{_fmt_time(w.observation_time)}</td>')
            parts.append(f'<td style="{_STYLE_TD}">{html.escape(w.model.upper())}</td>')
            parts.append(
                f'<td style="{_STYLE_TD}">'
                f"{html.escape(w.model_wind_advisory)}</td>"
            )
            parts.append("</tr>")
        parts.append("</table>")

    return "".join(parts)


# ---------------------------------------------------------------------------
# Plain text builder
# ---------------------------------------------------------------------------


def _build_digest_plain(data: VerificationDigestData) -> str:
    """Render the verification digest as plain text."""
    a = data.activity
    lines: list[str] = []

    label = data.period_label or "Daily"
    lines.append(f"FlyFun Verification Digest — {label}")
    lines.append("=" * 50)
    lines.append("")

    # Activity
    lines.append("ACTIVITY")
    lines.append(f"  Flights verified:  {a.flights_verified}")
    lines.append(f"  Flights completed: {a.flights_completed}")
    lines.append(f"  Airports observed: {a.airports_observed}")
    lines.append(f"  Observations:      {a.observations_collected}")
    lines.append(f"  Cycles:            {a.cycles_run}")
    if a.avg_cycle_duration_ms is not None:
        lines.append(f"  Avg cycle:         {a.avg_cycle_duration_ms:.0f}ms")
    lines.append("")

    # Category accuracy
    lines.append("FLIGHT CATEGORY ACCURACY")
    if data.category_accuracy_today:
        # Build table
        models_set: set[str] = set()
        for r in data.category_accuracy_today:
            models_set.add(r.model)
        models = sorted(m for m in models_set if m != "TAF")
        if "TAF" in models_set:
            models.append("TAF")

        header = f"{'Model':<10}" + "".join(f"{'D-' + str(d):>8}" for d in (0, 1, 2, 3, 5, 7))
        lines.append(header)
        lines.append("-" * len(header))

        today_map = {(r.model, r.days_out): r for r in data.category_accuracy_today}
        for model in models:
            row = f"{model.upper():<10}"
            for d in (0, 1, 2, 3, 5, 7):
                r = today_map.get((model, d))
                if r and r.accuracy_pct is not None:
                    row += f"{r.accuracy_pct:>7.0f}%"
                else:
                    row += f"{'—':>8}"
            lines.append(row)
    else:
        lines.append("  No data available.")
    lines.append("")

    # Notable misses
    if data.notable_misses:
        lines.append("NOTABLE MISSES")
        for m in data.notable_misses:
            ceiling = f" (ceiling {m.ceiling_delta_ft:+.0f}ft)" if m.ceiling_delta_ft is not None else ""
            lines.append(
                f"  {m.icao} {_fmt_time(m.observation_time)} — "
                f"{m.model.upper()}(D-{m.days_out}): {m.model_category}, "
                f"Actual: {m.obs_category}{ceiling}"
            )
        lines.append("")

    # Wind
    if data.wind_advisory:
        lines.append("WIND ADVISORY ACCURACY")
        for w in data.wind_advisory:
            pct = f"{w.accuracy_pct:.0f}%" if w.accuracy_pct is not None else "—"
            lines.append(f"  {w.model.upper():<10} {pct:>6}  (n={w.sample_count})")
        lines.append("")

    if data.missed_warnings:
        lines.append("MISSED WIND WARNINGS")
        for w in data.missed_warnings:
            lines.append(
                f"  {w.icao} {_fmt_time(w.observation_time)} — "
                f"{w.model.upper()}: predicted {w.model_wind_advisory}"
            )
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Send
# ---------------------------------------------------------------------------


def send_verification_digest(
    recipients: list[str],
    data: VerificationDigestData,
    *,
    smtp_config: SmtpConfig | None = None,
) -> None:
    """Build and send the verification digest email."""
    if not recipients:
        logger.debug("No recipients for verification digest, skipping")
        return

    label = data.period_label or "Daily"
    subject = f"[FlyFun] Verification Digest — {label}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = (
        smtp_config.from_address
        if smtp_config
        else "FlyFun Weather <noreply@flyfun.aero>"
    )
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText(_build_digest_plain(data), "plain", "utf-8"))
    msg.attach(MIMEText(_build_digest_html(data), "html", "utf-8"))

    send_message(msg, smtp_config)
    logger.info("Verification digest sent to %d recipient(s)", len(recipients))
