"""AROME 0.025° valid-domain band table.

PROVISIONAL — HAND-BUILT PLACEHOLDER, NOT DERIVED FROM DATA.

The real table is generated by ``scripts/regen_arome_domain.py`` from a
delivered AROME message's missing-value bitmap, which replaces this whole file
(see :mod:`weatherbrief.fetch.grib.arome_domain` for the format and rules).
That script could not be run when #529 was implemented: the build environment
had no network route to the Météo-France mirror.

Until it is regenerated, these bands are built from the edge measurements
recorded on issue #529 (2026-07-30), deliberately conservative:

- west edge −8.4° at 39°N → −11.5° at 53°N, linear in between;
- east edge mirrored about 2°E (the centre of the 55.38°N top arc, −0.5…4.5°)
  and capped at 15.5°E (15.95°E is verified outside);
- above 53°N both edges close linearly onto −0.5…4.5° at 55.38°N;
- no band south of 39°N (37.55°N/2°E is verified outside — the bottom edge
  bows north in the middle) or north of 55°N;
- every band is the intersection of its two edge latitudes, inset 0.75°.

Too narrow is safe (AROME is skipped and the slot stays Open-Meteo). Too wide
costs one download, then the decode-time stencil check fails the slot.
"""

SOURCE = "provisional: hand-built from #529 edge measurements, inset 0.75 deg"

# (lat_south, lat_north, west, east), south to north.
BANDS: tuple[tuple[float, float, float, float], ...] = (
    (39.0000, 39.5000, -7.6500, 11.6500),
    (39.5000, 40.0000, -7.7607, 11.7607),
    (40.0000, 40.5000, -7.8714, 11.8714),
    (40.5000, 41.0000, -7.9821, 11.9821),
    (41.0000, 41.5000, -8.0929, 12.0929),
    (41.5000, 42.0000, -8.2036, 12.2036),
    (42.0000, 42.5000, -8.3143, 12.3143),
    (42.5000, 43.0000, -8.4250, 12.4250),
    (43.0000, 43.5000, -8.5357, 12.5357),
    (43.5000, 44.0000, -8.6464, 12.6464),
    (44.0000, 44.5000, -8.7571, 12.7571),
    (44.5000, 45.0000, -8.8679, 12.8679),
    (45.0000, 45.5000, -8.9786, 12.9786),
    (45.5000, 46.0000, -9.0893, 13.0893),
    (46.0000, 46.5000, -9.2000, 13.2000),
    (46.5000, 47.0000, -9.3107, 13.3107),
    (47.0000, 47.5000, -9.4214, 13.4214),
    (47.5000, 48.0000, -9.5321, 13.5321),
    (48.0000, 48.5000, -9.6429, 13.6429),
    (48.5000, 49.0000, -9.7536, 13.7536),
    (49.0000, 49.5000, -9.8643, 13.8643),
    (49.5000, 50.0000, -9.9750, 13.9750),
    (50.0000, 50.5000, -10.0857, 14.0857),
    (50.5000, 51.0000, -10.1964, 14.1964),
    (51.0000, 51.5000, -10.3071, 14.3071),
    (51.5000, 52.0000, -10.4179, 14.4179),
    (52.0000, 52.5000, -10.5286, 14.5286),
    (52.5000, 53.0000, -10.6393, 14.6393),
    (53.0000, 53.5000, -8.4391, 12.4391),
    (53.5000, 54.0000, -6.1282, 10.1282),
    (54.0000, 54.5000, -3.8172, 7.8172),
    (54.5000, 55.0000, -1.5063, 5.5063),
)
