"""Météo-France AROME 0.025° domain predicate (issue #529).

AROME's 0.025° product is delivered on a 717×1121 regular lat/lon array over
37.5–55.4°N / 12°W–16°E, but only ~82.8 % of the cells carry data. The valid
region is a bowed quadrilateral that narrows southward (the footprint of the
model's own projected domain, resampled onto lat/lon), so neither the array's
bounding box nor a fitted Lambert rectangle is a usable "is this inside?"
test — the first accepts Ireland's west coast and the Adriatic, the second
leaves ~61 km of edge scatter.

The test used here is a table of latitude **bands**, each with the
``[west, east]`` longitude span that is valid across the WHOLE band. It is
data, generated by ``scripts/regen_arome_domain.py`` from a delivered AROME
message's own missing-value bitmap and checked in as
:mod:`weatherbrief.fetch.grib.arome_domain_bands`, so it can be regenerated
if Météo-France moves the domain.

Lives in its own module (no network, no GRIB imports) because two consumers
need the same predicate: the AROME GRIB enrichment in ``arome_fetch`` /
``fetch/grib/__init__``, and the narrow-only Open-Meteo gating of the
``meteofrance`` slot (routes fully inside AROME, not merely touching France).

The table is a pre-filter, not the last word. The AROME decode treats a
route point whose bilinear stencil touches a missing cell as uncovered and
fails the whole slot (see ``_decode_and_merge_arome``), so a table that is
slightly too generous costs one download, never a half-AROME briefing.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import NamedTuple

# Fraction of the 717×1121 array that carries data, measured 2026-07-30 on a
# live AROME 0.025° message. Decode compares every file it reads against this
# so a silent domain change shows up in the logs (and tells you to rerun the
# regeneration script) instead of quietly staling the band table.
AROME_EXPECTED_FINITE_FRACTION = 0.828
AROME_FINITE_FRACTION_TOLERANCE = 0.02


class DomainBand(NamedTuple):
    """One latitude band: ``[lat_south, lat_north]`` valid over ``[west, east]``."""

    lat_south: float
    lat_north: float
    west: float
    east: float


def _load_bands() -> tuple[tuple[DomainBand, ...], str]:
    from weatherbrief.fetch.grib import arome_domain_bands as data

    bands = tuple(DomainBand(*b) for b in data.BANDS)
    return bands, data.SOURCE


AROME_DOMAIN_BANDS, AROME_DOMAIN_SOURCE = _load_bands()


def arome_domain_is_provisional() -> bool:
    """True while the checked-in table is the hand-built placeholder.

    The generated table records the AROME run it was derived from in
    ``SOURCE``; the placeholder says ``provisional``. Enrichment logs a
    warning when it runs on the placeholder.
    """
    return AROME_DOMAIN_SOURCE.startswith("provisional")


def point_in_arome_domain(
    lat: float,
    lon: float,
    bands: Iterable[DomainBand] | None = None,
) -> bool:
    """True when ``(lat, lon)`` lies inside the valid AROME footprint.

    ``lon`` is in the −180..+180 convention route points use. A point on a
    band boundary is accepted if either adjacent band accepts it.
    """
    for band in bands if bands is not None else AROME_DOMAIN_BANDS:
        if band.lat_south <= lat <= band.lat_north and band.west <= lon <= band.east:
            return True
    return False


def route_in_arome_domain(
    route_points: Iterable,
    bands: Iterable[DomainBand] | None = None,
) -> bool:
    """True when EVERY route point is inside the AROME footprint.

    All-or-nothing, mirroring ``route_in_icon_eu_domain``: a single point
    outside means the route is not an AROME route. ``route_points`` are any
    objects with ``.lat`` / ``.lon`` (``RoutePoint``, ``Waypoint``).
    """
    band_list = tuple(bands) if bands is not None else AROME_DOMAIN_BANDS
    points = list(route_points)
    if not points:
        return False
    return all(point_in_arome_domain(p.lat, p.lon, band_list) for p in points)


def derive_domain_bands(
    lats,
    lons,
    finite,
    *,
    band_deg: float = 0.1,
) -> list[DomainBand]:
    """Build the band table from a grid's finite-cell mask.

    Used by ``scripts/regen_arome_domain.py``; kept here so the derivation is
    unit-tested rather than living only in a script.

    Args:
        lats: 1-D latitude axis (ascending or descending), length ``nj``.
        lons: 1-D longitude axis, −180..+180, length ``ni``.
        finite: Boolean array ``(nj, ni)``, True where the cell carries data.
        band_deg: Band height in degrees.

    Each grid row contributes its westernmost and easternmost finite cell,
    shrunk by ONE cell on each side: the decode interpolates bilinearly, so a
    point is only usable if both of its neighbouring columns are finite. A
    band's span is the intersection over every row it overlaps (plus the row
    just beyond each edge, for the same stencil reason), so any point inside
    a band is inside on every row near it. A band containing a row with no
    data, or a row whose finite cells are not one contiguous run, is dropped
    — the domain is convex in practice, and anything else means the input is
    not what this function assumes.

    Returns bands ordered south to north.
    """
    import numpy as np

    lat_arr = np.asarray(lats, dtype=np.float64)
    lon_arr = np.asarray(lons, dtype=np.float64)
    mask = np.asarray(finite, dtype=bool)
    if mask.shape != (lat_arr.size, lon_arr.size):
        raise ValueError(
            f"mask shape {mask.shape} != (len(lats), len(lons)) "
            f"({lat_arr.size}, {lon_arr.size})"
        )
    if lat_arr[0] > lat_arr[-1]:
        lat_arr = lat_arr[::-1]
        mask = mask[::-1, :]
    if lon_arr[0] > lon_arr[-1]:
        lon_arr = lon_arr[::-1]
        mask = mask[:, ::-1]

    # Per-row usable span, None for a row that has no usable span.
    row_span: list[tuple[float, float] | None] = []
    for row in mask:
        idx = np.flatnonzero(row)
        if idx.size < 3 or (idx[-1] - idx[0] + 1) != idx.size:
            row_span.append(None)
            continue
        row_span.append((float(lon_arr[idx[0] + 1]), float(lon_arr[idx[-1] - 1])))

    bands: list[DomainBand] = []
    lat_min, lat_max = float(lat_arr[0]), float(lat_arr[-1])
    start = np.floor(lat_min / band_deg) * band_deg
    edges = np.arange(start, lat_max + band_deg, band_deg)
    for south, north in zip(edges[:-1], edges[1:]):
        south = round(float(south), 6)
        north = round(float(north), 6)
        inside = np.flatnonzero((lat_arr >= south) & (lat_arr <= north))
        if inside.size == 0:
            continue
        lo = max(int(inside[0]) - 1, 0)
        hi = min(int(inside[-1]) + 1, lat_arr.size - 1)
        # Bands that reach the grid's first/last row cannot have the
        # outer-neighbour row the stencil needs; trim them to the rows that do.
        spans = row_span[lo:hi + 1]
        if lo == int(inside[0]) or hi == int(inside[-1]) or any(s is None for s in spans):
            continue
        west = max(s[0] for s in spans)
        east = min(s[1] for s in spans)
        if west >= east:
            continue
        bands.append(DomainBand(south, north, round(west, 4), round(east, 4)))
    return bands


def render_bands_module(bands: list[DomainBand], source: str) -> str:
    """Python source for ``arome_domain_bands.py`` (the regeneration output)."""
    lines = [
        '"""AROME 0.025° valid-domain band table — GENERATED, do not hand-edit.',
        "",
        "Regenerate with ``scripts/regen_arome_domain.py`` (see",
        ":mod:`weatherbrief.fetch.grib.arome_domain` for the format and the",
        'derivation rules)."""',
        "",
        f"SOURCE = {source!r}",
        "",
        "# (lat_south, lat_north, west, east), south to north.",
        "BANDS: tuple[tuple[float, float, float, float], ...] = (",
    ]
    for b in bands:
        lines.append(
            f"    ({b.lat_south:.4f}, {b.lat_north:.4f}, {b.west:.4f}, {b.east:.4f}),"
        )
    lines.append(")")
    return "\n".join(lines) + "\n"
