// AUTO-GENERATED by scripts/dump_chart_calibrations.py — do not edit by hand.
// Source of truth: _CHART_CALIBRATIONS in
//   src/weatherbrief/fetch/dwd_charts.py and metoffice_charts.py.
// Regenerate after any calibration change: python scripts/dump_chart_calibrations.py

export type ChartProjectionKey =
  | "dwd-analysis"
  | "dwd-icon"
  | "metoffice-colour";

export interface ChartProjectionConstants {
  /** Polar-stereographic origin latitude (deg); always 90 (north pole) here. */
  lat_0: number;
  /** Standard parallel (deg). */
  lat_ts: number;
  /** Central meridian (deg). */
  lon_0: number;
  /** 8-coefficient 2D homography [a,b,c,d,e,f,g,h]. */
  homography: readonly [number, number, number, number, number, number, number, number];
  /** Native chart pixel size [width, height]. */
  native_size: readonly [number, number];
}

/** Shared WGS84 ellipsoid used by all calibrations (pyproj default). */
export const WGS84 = {
  a: 6378137.0,
  e2: 0.0066943799901413165,
} as const;

export const CHART_PROJECTIONS: Record<ChartProjectionKey, ChartProjectionConstants> = {
  "dwd-analysis": {
    lat_0: 90,
    lat_ts: 90,
    lon_0: 10,
    homography: [0.0005145316041850823, 5.082539130306949e-06, 2793.4808547432303, 1.1777669359815649e-06, -0.0005125590704322343, -606.7192569143913, 8.930427981271965e-10, 1.7297125807436028e-09],
    native_size: [4389, 3114],
  },
  "dwd-icon": {
    lat_0: 90,
    lat_ts: 60,
    lon_0: 5,
    homography: [0.00010064544583772085, 8.021406574208543e-06, 505.2081110061641, 8.455010167934436e-06, -0.00010106842893807126, -114.44765418753545, -3.747121446686481e-10, -3.0137722186545355e-10],
    native_size: [800, 653],
  },
  "metoffice-colour": {
    lat_0: 90,
    lat_ts: 60,
    lon_0: 0,
    homography: [8.219263981133556e-05, -5.606207726787221e-05, 207.51767075737098, -5.659944858480127e-05, -8.104286158047984e-05, -51.726683330077734, 8.48991737686672e-10, 2.4811569193648073e-09],
    native_size: [800, 540],
  },
};
