"""Pydantic v2 models for weatherbrief.

Re-exports from submodules so ``from weatherbrief.models import X`` keeps working.
"""

from weatherbrief.models.analysis import (  # noqa: F401
    AgreementLevel,
    AltitudeAdvisories,
    AltitudeAdvisory,
    CATRiskLayer,
    CATRiskLevel,
    CloudCoverage,
    ConvectiveAssessment,
    ConvectiveRegime,
    ConvectiveRisk,
    DerivedLevel,
    ElevationPoint,
    ElevationProfile,
    EnhancedCloudLayer,
    ForecastSnapshot,
    HourlyForecast,
    IcingRisk,
    IcingType,
    IcingZone,
    InversionLayer,
    GlareAssessment,
    ModelDivergence,
    ModelSource,
    NightInterval,
    ParcelPathPoint,
    NWPCloudDiagnostics,
    NWPCloudLayerDiag,
    PrecipIntensity,
    PrecipPhase,
    PrecipitationAssessment,
    PrecipitationZone,
    PressureLevelData,
    RouteAnalysesManifest,
    RouteConfig,
    RouteCrossSection,
    RoutePoint,
    RoutePointAnalysis,
    RoutePointWindOverlay,
    RouteSunAnalysis,
    RouteWindOverlay,
    SfipZone,
    SunSideSegment,
    SunSideSummary,
    SldZone,
    SoundingAnalysis,
    ThermodynamicIndices,
    VerticalMotionAssessment,
    VerticalMotionClass,
    VerticalRegime,
    Waypoint,
    WaypointAnalysis,
    WaypointForecast,
    WindComponent,
    altitude_to_pressure_hpa,
    bearing_between,
    bearing_between_coords,
    pressure_hpa_to_altitude_m,
    pressure_pa_to_altitude_ft,
)
from weatherbrief.models.diagnostic import (  # noqa: F401
    DETAIL_MAX_BYTES,
    Diagnostic,
    DiagnosticLevel,
    DiagnosticPublic,
)
from weatherbrief.models.diagnostic_codes import (  # noqa: F401
    AdvisoryCode,
    DigestCode,
    FetchCode,
    GrametCode,
    SkewtCode,
)
from weatherbrief.models.advisories import (  # noqa: F401
    AdvisoryAggregation,
    AdvisoryCatalogEntry,
    AdvisoryParameterDef,
    AdvisoryStatus,
    AltitudeAdvisoryRow,
    AltitudeTableResult,
    ModelAdvisoryResult,
    RouteAdvisoriesManifest,
    RouteAdvisoryResult,
)
from weatherbrief.models.fronts import (  # noqa: F401
    FrontCrossingModel,
    FrontDecisionModel,
    FrontProximityModel,
    RouteFrontAnalysisModel,
    RouteFrontsManifest,
)
from weatherbrief.models.airport_conditions import (  # noqa: F401
    FLIGHT_CATEGORY_COLORS,
    AirportConditions,
    AirportConditionsSummary,
    AirportModelCondition,
    FlightCategory,
    RunwayEnd,
    RunwayWind,
)
from weatherbrief.models.alternates import (  # noqa: F401
    ALT_AXIS_LABELS,
    AlternateAirport,
    AlternateAxisPick,
    RouteAlternates,
)
from weatherbrief.models.observations import (  # noqa: F401
    AirportObservation,
    ObservationComparison,
    RealtimeRefreshResult,
    RouteObservations,
    RouteSigmets,
    SigmetAlongRoute,
)
from weatherbrief.models.storage import (  # noqa: F401
    BriefingPackMeta,
    Flight,
    FlightDebrief,
    FlightProfile,
    NOTE_MAX_LEN,
)
