/**
 * Equivalence test: the TS chart projection must match the Python (pyproj)
 * path within 1 px, and round-trip (forward -> inverse -> forward) within 1 px.
 *
 * Fixture is auto-generated by scripts/dump_chart_calibrations.py.
 */

import { describe, it, expect } from 'vitest';
import { makeChartProjection } from '../../ts/visualization/chart-projection';
import type { ChartProjectionKey } from '../../ts/visualization/chart-projection-constants';
import fixture from './fixtures/chart-projection.json';

interface FixturePoint {
  key: ChartProjectionKey;
  lat: number;
  lon: number;
  x: number;
  y: number;
  px: number;
  py: number;
}

const points = fixture.points as FixturePoint[];
const keys = [...new Set(points.map((p) => p.key))];

describe('chart projection forward equivalence with pyproj', () => {
  for (const key of keys) {
    const proj = makeChartProjection(key);
    const pts = points.filter((p) => p.key === key);

    // Threshold is 1.5 px, not 1: the fixture stores Python's int()-truncated
    // pixels (up to ~1 px below the true value), and the TS port keeps the
    // sub-pixel fraction — so a faithful match differs by up to ~1 px.
    it(`${key}: forward matches Python within 1.5 px (${pts.length} points)`, () => {
      for (const p of pts) {
        const out = proj.forward(p.lat, p.lon);
        expect(Math.abs(out.x - p.px), `dx at (${p.lat},${p.lon})`).toBeLessThan(1.5);
        expect(Math.abs(out.y - p.py), `dy at (${p.lat},${p.lon})`).toBeLessThan(1.5);
      }
    });
  }
});

describe('makeChartProjection guards', () => {
  it('throws on an unknown projection key (no silent NaN)', () => {
    expect(() => makeChartProjection('bogus-key' as ChartProjectionKey)).toThrow();
  });
});

describe('chart projection inverse round-trip', () => {
  for (const key of keys) {
    const proj = makeChartProjection(key);
    const pts = points.filter((p) => p.key === key);

    it(`${key}: forward -> inverse -> forward within 1 px`, () => {
      for (const p of pts) {
        const fwd = proj.forward(p.lat, p.lon);
        const ll = proj.inverse(fwd.x, fwd.y);
        const again = proj.forward(ll.lat, ll.lon);
        expect(Math.abs(again.x - fwd.x), `rt x at (${p.lat},${p.lon})`).toBeLessThan(1);
        expect(Math.abs(again.y - fwd.y), `rt y at (${p.lat},${p.lon})`).toBeLessThan(1);
        // And the recovered lon/lat should be close to the original.
        expect(Math.abs(ll.lat - p.lat), `rt lat at (${p.lat},${p.lon})`).toBeLessThan(0.01);
        expect(Math.abs(ll.lon - p.lon), `rt lon at (${p.lat},${p.lon})`).toBeLessThan(0.01);
      }
    });
  }
});
