/**
 * Equivalence test: the TS chart projection must match the Python (pyproj)
 * path within 1 px, and round-trip (forward -> inverse -> forward) within 1 px.
 *
 * Fixture is auto-generated by scripts/dump_chart_calibrations.py.
 */

import { describe, it, expect } from 'vitest';
import { makeChartProjection } from '../../ts/visualization/chart-projection';
import type { ChartProjectionKey } from '../../ts/visualization/chart-projection-constants';
import fixture from './fixtures/chart-projection.json';

interface FixturePoint {
  key: ChartProjectionKey;
  lat: number;
  lon: number;
  x: number;
  y: number;
  px: number;
  py: number;
}

const points = fixture.points as FixturePoint[];
const keys = [...new Set(points.map((p) => p.key))];

describe('chart projection forward equivalence with pyproj', () => {
  for (const key of keys) {
    const proj = makeChartProjection(key);
    const pts = points.filter((p) => p.key === key);

    it(`${key}: forward matches Python within 1 px (${pts.length} points)`, () => {
      let worst = 0;
      for (const p of pts) {
        const out = proj.forward(p.lat, p.lon);
        // Python casts to int() (truncation toward zero); allow that plus a
        // sub-pixel numerical margin.
        const dx = Math.abs(out.x - p.px);
        const dy = Math.abs(out.y - p.py);
        worst = Math.max(worst, dx, dy);
        expect(dx, `dx at (${p.lat},${p.lon})`).toBeLessThan(1.5);
        expect(dy, `dy at (${p.lat},${p.lon})`).toBeLessThan(1.5);
      }
      // Sanity: the bulk should be essentially exact (the 1px-ish slack is only
      // Python's int() truncation), so worst case stays small.
      expect(worst).toBeLessThan(1.5);
    });
  }
});

describe('chart projection inverse round-trip', () => {
  for (const key of keys) {
    const proj = makeChartProjection(key);
    const pts = points.filter((p) => p.key === key);

    it(`${key}: forward -> inverse -> forward within 1 px`, () => {
      for (const p of pts) {
        const fwd = proj.forward(p.lat, p.lon);
        const ll = proj.inverse(fwd.x, fwd.y);
        const again = proj.forward(ll.lat, ll.lon);
        expect(Math.abs(again.x - fwd.x), `rt x at (${p.lat},${p.lon})`).toBeLessThan(1);
        expect(Math.abs(again.y - fwd.y), `rt y at (${p.lat},${p.lon})`).toBeLessThan(1);
        // And the recovered lon/lat should be close to the original.
        expect(Math.abs(ll.lat - p.lat), `rt lat at (${p.lat},${p.lon})`).toBeLessThan(0.01);
        expect(Math.abs(ll.lon - p.lon), `rt lon at (${p.lat},${p.lon})`).toBeLessThan(0.01);
      }
    });
  }
});
