#!/usr/bin/env python3
"""Generate the TypeScript chart-projection constants + an equivalence fixture.

Reads the canonical ``_CHART_CALIBRATIONS`` / ``CHART_NATIVE_SIZE`` from both
chart-cache modules and emits:

  1. ``web/ts/visualization/chart-projection-constants.ts`` — the projection
     params (polar-stereo lat_0/lat_ts/lon_0, the 8-coeff homography,
     native size) and the shared WGS84 ellipsoid, keyed by chart type
     (``dwd-analysis`` / ``dwd-icon`` / ``metoffice-colour``).
  2. ``web/tests/unit/fixtures/chart-projection.json`` — reference
     ``(lat, lon) -> raw projected (x, y) -> pixel (px, py)`` pairs computed
     by the *Python* (pyproj) path, so the TS port can be checked for 1-px
     equivalence and its raw projection isolated when debugging.

Run after any calibration change::

    python scripts/dump_chart_calibrations.py

Commit all three of: this script's two outputs and the source calibration.
"""

from __future__ import annotations

import json
from pathlib import Path

import pyproj

from weatherbrief.fetch import dwd_charts, metoffice_charts

REPO_ROOT = Path(__file__).resolve().parent.parent
TS_OUT = REPO_ROOT / "web" / "ts" / "visualization" / "chart-projection-constants.ts"
FIXTURE_OUT = REPO_ROOT / "web" / "tests" / "unit" / "fixtures" / "chart-projection.json"

# Chart-type registry: stable TS key -> (module, chart_type).
SOURCES: list[tuple[str, object, str]] = [
    ("dwd-analysis", dwd_charts, "analysis"),
    ("dwd-icon", dwd_charts, "icon"),
    ("metoffice-colour", metoffice_charts, "colour"),
]

# Reference points: dense over the Hewson European domain + a few extremes that
# exercise the homography edges. (lat, lon).
_LATS = [35.0, 40.0, 45.0, 50.0, 55.0, 60.0]
_LONS = [-20.0, -12.0, -4.0, 4.0, 12.0, 20.0, 28.0]
_EXTREMES = [(30.0, -25.0), (65.0, 30.0), (62.0, -24.0), (32.0, 27.0)]


def _ref_points() -> list[tuple[float, float]]:
    pts = [(lat, lon) for lat in _LATS for lon in _LONS]
    pts.extend(_EXTREMES)
    return pts


def _calibrations(module: object) -> dict:
    return module._CHART_CALIBRATIONS  # type: ignore[attr-defined]


def _native_sizes(module: object) -> dict:
    return module.CHART_NATIVE_SIZE  # type: ignore[attr-defined]


def build_constants() -> dict:
    out: dict[str, dict] = {}
    for key, module, chart_type in SOURCES:
        cal = _calibrations(module)[chart_type]
        size = _native_sizes(module)[chart_type]
        proj = cal["proj"]
        out[key] = {
            "lat_0": proj["lat_0"],
            "lat_ts": proj["lat_ts"],
            "lon_0": proj["lon_0"],
            "homography": list(cal["homography"]),
            "native_size": list(size),
        }
    return out


def _ellipsoid() -> dict:
    # All three calibrations use pyproj's default WGS84 ellipsoid.
    crs = pyproj.Proj(proj="stere", lat_0=90, lat_ts=60, lon_0=0).crs
    a = crs.ellipsoid.semi_major_metre
    inv_f = crs.ellipsoid.inverse_flattening
    f = 1.0 / inv_f
    e2 = 2 * f - f * f
    return {"a": a, "inv_f": inv_f, "e2": e2}


def write_ts(constants: dict, ellipsoid: dict) -> None:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by scripts/dump_chart_calibrations.py — do not edit by hand.")
    lines.append("// Source of truth: _CHART_CALIBRATIONS in")
    lines.append("//   src/weatherbrief/fetch/dwd_charts.py and metoffice_charts.py.")
    lines.append("// Regenerate after any calibration change: python scripts/dump_chart_calibrations.py")
    lines.append("")
    lines.append("export type ChartProjectionKey =")
    keys = list(constants.keys())
    for i, k in enumerate(keys):
        sep = ";" if i == len(keys) - 1 else ""
        lines.append(f"  | {json.dumps(k)}{sep}")
    lines.append("")
    lines.append("export interface ChartProjectionConstants {")
    lines.append("  /** Polar-stereographic origin latitude (deg); always 90 (north pole) here. */")
    lines.append("  lat_0: number;")
    lines.append("  /** Standard parallel (deg). */")
    lines.append("  lat_ts: number;")
    lines.append("  /** Central meridian (deg). */")
    lines.append("  lon_0: number;")
    lines.append("  /** 8-coefficient 2D homography [a,b,c,d,e,f,g,h]. */")
    lines.append("  homography: readonly [number, number, number, number, number, number, number, number];")
    lines.append("  /** Native chart pixel size [width, height]. */")
    lines.append("  native_size: readonly [number, number];")
    lines.append("}")
    lines.append("")
    lines.append("/** Shared WGS84 ellipsoid used by all calibrations (pyproj default). */")
    lines.append("export const WGS84 = {")
    lines.append(f"  a: {ellipsoid['a']!r},")
    lines.append(f"  e2: {ellipsoid['e2']!r},")
    lines.append("} as const;")
    lines.append("")
    lines.append(
        "export const CHART_PROJECTIONS: "
        "Record<ChartProjectionKey, ChartProjectionConstants> = {"
    )
    for key in keys:
        c = constants[key]
        homog = ", ".join(repr(v) for v in c["homography"])
        size = ", ".join(str(v) for v in c["native_size"])
        lines.append(f"  {json.dumps(key)}: {{")
        lines.append(f"    lat_0: {c['lat_0']!r},")
        lines.append(f"    lat_ts: {c['lat_ts']!r},")
        lines.append(f"    lon_0: {c['lon_0']!r},")
        lines.append(f"    homography: [{homog}],")
        lines.append(f"    native_size: [{size}],")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text("\n".join(lines))
    print(f"wrote {TS_OUT.relative_to(REPO_ROOT)}")


def write_fixture(ellipsoid: dict) -> None:
    points: list[dict] = []
    for key, module, chart_type in SOURCES:
        for lat, lon in _ref_points():
            x, y = pyproj.Proj(
                **_calibrations(module)[chart_type]["proj"]
            )(lon, lat)
            px, py = module.lonlat_to_chart_pixel(lon, lat, chart_type)  # type: ignore[attr-defined]
            points.append({
                "key": key,
                "lat": lat,
                "lon": lon,
                "x": x,
                "y": y,
                "px": px,
                "py": py,
            })
    fixture = {"ellipsoid": ellipsoid, "points": points}
    FIXTURE_OUT.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_OUT.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"wrote {FIXTURE_OUT.relative_to(REPO_ROOT)} ({len(points)} points)")


def main() -> None:
    ellipsoid = _ellipsoid()
    constants = build_constants()
    write_ts(constants, ellipsoid)
    write_fixture(ellipsoid)


if __name__ == "__main__":
    main()
